version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5450:5432"
    networks:
      - backend
      - webnet

  streamlit:
    build: .
    depends_on:
      - db
    ports:
      - "8505:8505"
    expose:
      - "8505"
    networks:
      - backend
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - streamlit
    networks:
      - webnet

volumes:
  pgdata:

networks:
  backend:
  webnet:


