version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8505:8505"
    expose:
      - "8505"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - streamlit
    networks:
      - webnet

networks:
  webnet:


